language: go
go:
  - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - curl -o build-prod.tar.gz -L https://github.com/andrexus/cloud-initer-frontend/releases/download/v0.1.0/build-prod.tar.gz
  - tar xzf build-prod.tar.gz
