language: go

go:
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

script:
  - FRONTEND_VERSION=0.1.3 curl -o build-prod.tar.gz -L \
      https://github.com/andrexus/cloud-initer-frontend/releases/download/v$FRONTEND_VERSION/build-prod.tar.gz
  - tar xzf build-prod.tar.gz
  - make test build dist