[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.1"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"

[[constraint]]
  name = "github.com/aymerick/raymond"
  version = "2.0.1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "0.11.5"

[[constraint]]
  name = "github.com/xlab/closer"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
